name: centos7

on: [ push, pull_request ]

jobs:
  build:
    environment: gha-ci
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04 ]
    steps:
      - uses: actions/checkout@v2

      - name: set up terraform ${{ matrix.os }}
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: aws creds
        run: |
          mkdir -vp ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: set centos7 deploy
        run: |
          sed -i 's/enterprise/centos7/' terraform.tfvars
          sed -i 's/v0.3.8/v1.0.2/' terraform.tfvars
          cat terraform.tfvars
        working-directory: amazon_aws_enterprise

      - name: terraform enterprise aws fmt check
        run: terraform fmt -check
        working-directory: amazon_aws_enterprise

      - name: terraform enterprise aws init
        run: terraform init
        working-directory: amazon_aws_enterprise

      - name: terraform enterprise aws plan
        run: terraform plan
        working-directory: amazon_aws_enterprise
        if: false  # disable centos

      - name: trigger codebuild lucidum-deployment-pipelines centos
        run: echo trigger codebuild lucidum-deployment-pipelines centos

      - name: publish to slack
        run: |
          env
          echo publish ci job to slack
