name: ubuntu18

on: [ push, pull_request ]

jobs:
  build:
    environment: gha-ci
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04 ]
    steps:
      - uses: actions/checkout@v2

      - name: set up terraform ${{ matrix.os }}
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: aws creds
        run: |
          mkdir -vp ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: terraform fmt
        run: terraform fmt -check
        id: enterprise-aws-fmt
        working-directory: amazon_aws_enterprise

      - name: terraform init
        run: terraform init
        id: enterprise-aws-init
        working-directory: amazon_aws_enterprise

      - name: terraform plan
        run: terraform plan
        id: enterprise-aws-plan
        working-directory: amazon_aws_enterprise

      - name: trigger codebuild lucidum-deployment-pipelines ubuntu18
        run: echo trigger codebuild lucidum-deployment-pipelines ubuntu18

      - name: publish to slack
        run: |
          env
          echo publish ci job to slack
