name: azure

on: [ push, pull_request ]

jobs:
  build:
    environment: gha-ci
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04 ]
    steps:
      - uses: actions/checkout@v2

      - name: set up terraform ${{ matrix.os }}
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        continue-on-error: true

      - name: terraform enterprise azure fmt check
        run: terraform fmt -check
        id: enterprise-azure-fmt
        working-directory: microsoft_azure

      - name: terraform enterprise azure init
        run: terraform init
        id: enterprise-azure-init
        working-directory: microsoft_azure
        continue-on-error: true

      - name: terraform enterprise azure plan
        run: terraform plan
        id: enterprise-azure-plan
        working-directory: microsoft_azure
        continue-on-error: true

      - name: publish to slack
        run: |
          env
          echo publish ci job to slack
