name: lucidum-deployment-seed continuous integration

on: [ push, pull_request ]

jobs:
  build:
    environment: gha-ci
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04 ]
    defaults:
      run:
        working-directory: amazon_aws_community
    steps:
      - uses: actions/checkout@v2

      - name: set up terraform ${{ matrix.os }}
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: terraform fmt check
        run: terraform fmt -check
        id: fmt

      - name: aws creds
        run: |
          mkdir -vp ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: terraform init
        run: terraform init 
        id: init

      - name: terraform plan
        run: terraform plan
        id: plan

      - name: trigger codebuild lucidum-deployment-pipelines
        run: echo trigger codebuild lucidum-deployment-pipelines

      - name: publish to slack
        run: echo publish ci job to slack
