name: lucidum-deployment-seed continuous integration

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04 ]
    steps:
      - uses: actions/checkout@v2

      - name: set up terraform ${{ matrix.os }}
        uses: hashicorp/setup-terraform@v1.2.1

      - name: lint
        run: echo lint

      - name: aws creds
        run: |
          mkdir -vp ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
      - name: terraform plan
        run: terraform plan
        env:
          TF_VAR_associate_public_ip_address: false
          #{ "name"="ENVIRONMENT", "type"="PLAINTEXT", "value"="dev" },
          #{ "name"="AWS_REGION", "type"="PLAINTEXT", "value"=var.aws_region },
          #{ "name"="TERRAFORM_VERSION", "type"="PLAINTEXT", "value"=var.terraform_version },
          #{ "name"="LUCIDUM_DEPLOY", "type"="PLAINTEXT", "value"=var.lucidum_deploy_repo },
          #{ "name"="PLAYBOOK_EDITION", "type"="PLAINTEXT", "value"="ubuntu18" },
          #{ "name"="PLAYBOOK_VERSION", "type"="PLAINTEXT", "value"=var.playbook_version },
          #{ "name"="AVAILABILITY_ZONE", "type"="PLAINTEXT", "value"=var.availability_zone },
          #{ "name"="SOURCE_AMI_ACCOUNT_NUMBER", "type"="PLAINTEXT", "value"=var.source_ami_account_number },
          #{ "name"="INSTANCE_SIZE", "type"="PLAINTEXT", "value"=var.instance_size },
          #{ "name"="SUBNET_ID", "type"="PLAINTEXT", "value"=var.subnet_ids[0] },
          #{ "name"="VPC_ID", "type"="PLAINTEXT", "value"=var.vpc_id },
          #{ "name"="KEY_NAME", "type"="PLAINTEXT", "value"=var.key_name },


      - name: terraform apply
        run: echo terraform apply

      - name: publish to slack
        run: echo publish ci job to slack
